# Generated by Django 4.2.4 on 2023-09-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0004_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.CreateModel(
            name='preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiones', models.CharField(choices=[('muy pequeño', 'Muy pequeño'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('muy grande', 'Muy grande')])),
                ('ciclo', models.CharField(choices=[('annual', 'Que viva un año'), ('biannual', 'Que dura 6 meses'), ('perennial', 'Que puedad vivir decadas o siglos'), ('biennial', 'Que vive dos años')])),
                ('riego', models.CharField(choices=[('frequent', 'Frecuente'), ('average', 'Promedio'), ('minimum', 'Minimo'), ('none', 'Nunca')])),
                ('requerimiento_de_agua', models.CharField(choices=[('mucho', 'Mucho'), ('regular', 'Regular'), ('poco', 'Poco'), ('nada', 'Nada')])),
                ('periodo_de_riego', models.CharField(choices=[('morning', 'Mañana'), ('afternnon', 'Tarde'), ('evening', 'Noche')])),
                ('flores', models.CharField(choices=[(True, 'Sí'), (False, 'No')])),
                ('luz_solar', models.CharField(choices=[('full_shade', 'Sombra'), ('part_shade', 'Parcialmente con sombra'), ('sun-part_shade', 'Sol y sombra'), ('full_sun', 'Sol')])),
                ('fruta', models.CharField(choices=[(True, 'Sí'), (False, 'No')])),
                ('medicinal', models.CharField(choices=[(True, 'Sí'), (False, 'No')])),
                ('venenoso_humano', models.CharField(choices=[(False, 'Sí'), (True, 'No')])),
                ('venenoso_mascota', models.CharField(choices=[(False, 'Sí'), (True, 'No')])),
                ('tropical', models.CharField(choices=[(True, 'Sí'), (False, 'No')])),
                ('interior', models.CharField(choices=[(True, 'Sí'), (False, 'No')])),
                ('nivel_de_atencion', models.CharField(choices=[('Low', 'Bajo'), ('Medium', 'Mediano'), ('High', 'Alto')])),
                ('conexion', models.ForeignKey(db_column='nombre', on_delete=django.db.models.deletion.CASCADE, to='nombreapp.usuario')),
            ],
        ),
    ]
