# Generated by Django 4.2.4 on 2023-09-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0005_usuario_contraseña_alter_usuario_correo_preferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=120),
        ),
    ]
