# Generated by Django 4.2.4 on 2023-09-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0006_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='ciclo',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='dimensiones',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='flores',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='fruta',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='interior',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='luz_solar',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='medicinal',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='nivel_de_atencion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='periodo_de_riego',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='requerimiento_de_agua',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='riego',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='tropical',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='venenoso_humano',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='venenoso_mascota',
            field=models.CharField(),
        ),
    ]
