# Generated by Django 4.2.4 on 2023-09-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0007_alter_preferencias_ciclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='conexion',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='flores',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='fruta',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='luz_solar',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='medicinal',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='nivel_de_atencion',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='periodo_de_riego',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='requerimiento_de_agua',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='riego',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='tropical',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='venenoso_humano',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='venenoso_mascota',
        ),
    ]
