# Generated by Django 4.2.4 on 2023-09-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0008_remove_preferencias_conexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='flores',
            field=models.CharField(default='no'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='fruta',
            field=models.CharField(default='no'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='interior',
            field=models.CharField(default='no'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='luz_solar',
            field=models.CharField(default='sombra'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='medicinal',
            field=models.CharField(default='no'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='nivel_de_atencion',
            field=models.CharField(default='alto'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='periodo_de_riego',
            field=models.CharField(default='mañana'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='requerimiento_de_agua',
            field=models.CharField(default='mucho'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='riego',
            field=models.CharField(default='frecuente'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='tropical',
            field=models.CharField(default='no'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='venenoso_humano',
            field=models.CharField(default='si'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='venenoso_mascota',
            field=models.CharField(default='si'),
        ),
    ]
