# Generated by Django 4.2.4 on 2023-09-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0009_preferencias_conexion_preferencias_flores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='conexion',
            field=models.ForeignKey(db_column='nombre', default='1', on_delete=django.db.models.deletion.CASCADE, to='nombreapp.usuario'),
        ),
    ]
