# Generated by Django 4.2.4 on 2023-10-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0011_alter_preferencias_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='conexion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='preferencias',
        ),
    ]
