# Generated by Django 4.2.4 on 2023-10-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nombreapp', '0012_remove_preferencias_conexion_delete_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiones', models.CharField()),
                ('ciclo', models.CharField()),
                ('riego', models.CharField(default='frecuente')),
                ('requerimiento_de_agua', models.CharField(default='mucho')),
                ('periodo_de_riego', models.CharField(default='mañana')),
                ('flores', models.CharField(default='no')),
                ('luz_solar', models.CharField(default='sombra')),
                ('fruta', models.CharField(default='no')),
                ('medicinal', models.CharField(default='no')),
                ('venenoso_humano', models.CharField(default='si')),
                ('venenoso_mascota', models.CharField(default='si')),
                ('tropical', models.CharField(default='no')),
                ('interior', models.CharField(default='no')),
                ('nivel_de_atencion', models.CharField(default='alto')),
                ('conexion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia',
                'verbose_name_plural': 'Preferencias',
                'db_table': 'Preferencia',
                'ordering': ['conexion'],
            },
        ),
    ]
