# Generated by Django 4.2.4 on 2023-09-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0012_alter_preferencias_conexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='conexion',
            field=models.ForeignKey(default='nombre4', on_delete=django.db.models.deletion.CASCADE, to='nombreapp.usuario'),
        ),
    ]
