# Generated by Django 4.2.4 on 2023-09-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0015_remove_preferencias_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='conexion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nombreapp.usuario'),
        ),
    ]
