# Generated by Django 4.2.4 on 2023-09-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0016_preferencias_conexion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='conexion',
        ),
    ]
