# Generated by Django 4.2.4 on 2023-09-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0018_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
