# Generated by Django 4.2.4 on 2023-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0020_alter_preferencias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
